name: zero-downtime redeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add SSH Host Key
      run: |
        echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

    - name: Deploy to VPS
      env:
        VPS_HOST: ${{ secrets.HOST }}
        VPS_USER: tradeloop
      run: |
        ssh $VPS_USER@$VPS_HOST '
          cd tradeloop-functions
          git pull git@github.com:ajayvignesh01/tradeloop-functions.git
          ./upgrade.sh
        '