name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        node-version: 20
    - name: Deploy to VPS
      env:
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        ssh $USER@$HOST << EOF
          $PASSWORD
          cd tradeloop-functions
          git pull --rebase origin main
        EOF