name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Get host key
      run: |
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
  
    - name: Disable host key checking
      run: |
        echo "StrictHostKeyChecking no" >> ~/.ssh/config

    - name: Deploy to VPS
      env:
        VPS_HOST: ${{ secrets.HOST }}
        VPS_USER: tradeloop
      run: |
        ssh $VPS_USER@$VPS_HOST '
          cd tradeloop-functions
          git pull git@github.com:ajayvignesh01/tradeloop-functions.git
        '